using System.Windows;

namespace TwitchChatMvp.Services;

public static class LocalizationService
{
    public const string Russian = "ru-RU";
    public const string English = "en-US";

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["AppName"] = AppInfo.Name,
        ["AppTitle"] = AppInfo.Name,
        ["VersionLine"] = "версия " + AppInfo.Version,
        ["Settings"] = "Настройки",
        ["SettingsIntro"] = "Разделы сгруппированы для стрима: программа, чат, логи чата, OBS оверлей, Twitch аккаунт, донат и дополнительные параметры.",
        ["ConnectTwitch"] = "Подключить Twitch",
        ["ConnectTwitchIntro"] = "Выберите полный вход через Twitch или режим просмотра канала без авторизации.",
        ["FullAccessDescription"] = "Полный доступ: писать сообщения, модерировать чат и управлять каналом.",
        ["WatchChannelWithoutSignIn"] = "Смотреть канал без входа",
        ["WatchOnlyDescription"] = "Только чтение чата. Отправка сообщений и модерация будут недоступны.",
        ["TwitchChannelName"] = "Ник канала Twitch",
        ["TwitchChannelNameRequired"] = "Введите ник Twitch-канала.",
        ["ChannelSearchOffline"] = "Не в эфире",
        ["ChannelSearchNoResults"] = "Каналы не найдены",
        ["ChannelSearchUnavailableWithoutAuth"] = "Онлайн-поиск недоступен без авторизации",
        ["WatchOnlyMode"] = "Режим просмотра",
        ["WatchOnlySendingUnavailable"] = "В режиме просмотра отправка сообщений недоступна",
        ["SignInToSend"] = "Войти для отправки",
        ["ChangeWatchChannel"] = "Сменить канал просмотра",
        ["DisconnectFromChannel"] = "Отключиться от канала",
        ["WatchOnlyConnectFailed"] = "Не удалось подключиться к чату в режиме просмотра.",
        ["FullAccessMode"] = "Полный доступ",
        ["CurrentMode"] = "Текущий режим",
        ["LastReadOnlyChannel"] = "Последний канал просмотра",
        ["Connect"] = "Подключить",
        ["ChatReady"] = "Чат подключён. Новые сообщения появятся здесь.",
        ["OAuthPort"] = "OAuth port",
        ["TwitchOAuthPortBusyTitle"] = "Twitch OAuth port занят",
        ["OAuthPortBusy"] = "Порт авторизации Twitch занят другим приложением.\nИзмените OAuth port в настройках или закройте приложение, которое использует этот порт.",
        ["OAuthOverlayPortConflict"] = "OAuth port и OBS overlay port не должны совпадать.",
        ["ChangeOAuthPortInSettings"] = "Измените OAuth port в настройках.",
        ["Program"] = "Программа",
        ["Chat"] = "Чат",
        ["ChatLogs"] = "Логи чата",
        ["Channels"] = "Каналы",
        ["Streams"] = "Стримы",
        ["Search"] = "Поиск",
        ["User"] = "Пользователь",
        ["OpenFolder"] = "Открыть папку",
        ["ExportTxt"] = "Экспорт TXT",
        ["ExportJsonl"] = "Экспорт JSONL",
        ["DeleteLog"] = "Удалить лог",
        ["Messages"] = "Сообщений",
        ["StreamTitle"] = "Название стрима",
        ["StreamDate"] = "Дата стрима",
        ["LoggingEnabled"] = "Логирование включено. Приложение сохраняет только публичные сообщения чата, без токенов, OAuth-данных и приватных настроек.",
        ["EnableChatLogging"] = "Включить логирование чата",
        ["LogsFolder"] = "Папка логов",
        ["OpenLogsFolder"] = "Открыть папку логов",
        ["SaveJsonl"] = "Сохранять JSONL",
        ["SaveTxt"] = "Сохранять TXT",
        ["LogBadges"] = "Сохранять badges",
        ["LogDeletedMessages"] = "Сохранять удалённые сообщения",
        ["MaxLogViewerMessages"] = "Лимит сообщений в просмотрщике",
        ["AutoSplitLogsByStream"] = "Разделять логи по стримам",
        ["NoChatLogs"] = "Логи чата пока не найдены",
        ["LoadingLogs"] = "Загружаю логи...",
        ["ChatLogWriteFailed"] = "Не удалось записать лог чата. Проверьте папку логов.",
        ["DeleteLogConfirm"] = "Удалить выбранную сессию логов? Это действие нельзя отменить.",
        ["AllRoles"] = "Все роли",
        ["BroadcasterRole"] = "Владелец канала",
        ["ModeratorRole"] = "Модератор",
        ["SubscriberRole"] = "Подписчик",
        ["VipRole"] = "VIP",
        ["ObsOverlay"] = "OBS оверлей",
        ["TwitchAccount"] = "Twitch / Аккаунт",
        ["Donate"] = "Донат",
        ["Advanced"] = "Дополнительно",
        ["Language"] = "Язык",
        ["Theme"] = "Тема",
        ["Dark"] = "Тёмная",
        ["Light"] = "Светлая",
        ["SoundsDisabled"] = "Звуки приложения отключены",
        ["SoundsHelp"] = "Ошибки и предупреждения показываются визуально, без системных звуков Windows.",
        ["ToastNotifications"] = "Визуальные уведомления",
        ["ReduceMotion"] = "Уменьшить анимации",
        ["FontSize"] = "Размер шрифта",
        ["MessageLimit"] = "Лимит сообщений",
        ["ShowTimestamps"] = "Показывать время",
        ["ShowBadges"] = "Показывать Twitch badges",
        ["EnableTwitchEmotes"] = "Включить Twitch emotes",
        ["EnableBttvEmotes"] = "Включить BTTV emotes",
        ["EnableSevenTvEmotes"] = "Включить 7TV emotes",
        ["EnableObsOverlay"] = "Включить оверлей",
        ["OverlayUrl"] = "Overlay URL",
        ["CopyUrl"] = "Скопировать URL",
        ["OverlayPort"] = "Порт оверлея",
        ["OverlayMaxMessages"] = "Максимум сообщений в оверлее",
        ["OverlayFontSize"] = "Размер шрифта",
        ["FadeOutSeconds"] = "Исчезновение сообщений, секунд",
        ["FadeOutHint"] = "0 = не исчезают",
        ["BackgroundOpacity"] = "Прозрачность фона",
        ["Align"] = "Выравнивание",
        ["Left"] = "Слева",
        ["Center"] = "По центру",
        ["Right"] = "Справа",
        ["ShowEmotes"] = "Показывать emotes",
        ["TextShadow"] = "Тень текста",
        ["TestOverlayMessage"] = "Тестовое сообщение",
        ["LogoutTwitch"] = "Выйти из Twitch",
        ["ReconnectChat"] = "Переподключить чат",
        ["ChannelMode"] = "Режим канала",
        ["UseCustomChannel"] = "Подключаться к другому каналу, где я модератор",
        ["ChannelLogin"] = "Логин канала",
        ["BroadcasterId"] = "Broadcaster ID",
        ["AdvancedIntro"] = "Эти настройки нужны для разработки, кастомного Twitch Client ID или точной настройки OAuth.",
        ["UseCustomClientId"] = "Использовать свой Twitch Client ID",
        ["CustomClientId"] = "Свой Twitch Client ID",
        ["OAuthRedirectUri"] = "OAuth Redirect URI",
        ["RedirectHelp"] = "Должен совпадать с Redirect URL в Twitch Developer Console. По умолчанию: http://localhost:17654/. OBS оверлей использует отдельный порт http://localhost:17655/overlay/chat.",
        ["SupportDeveloper"] = "Поддержать разработчика",
        ["SupportDeveloperDescription"] = "Вы можете поддержать развитие WitherChat удобным способом.",
        ["Open"] = "Открыть",
        ["Copy"] = "Копировать",
        ["AddressCopied"] = "Адрес скопирован",
        ["Boosty"] = "Boosty",
        ["DonationAlerts"] = "DonationAlerts",
        ["Twitch"] = "Twitch",
        ["YouTube"] = "YouTube",
        ["UsdtTrc20"] = "USDT TRC20",
        ["UsdtTon"] = "USDT TON",
        ["UsdtTrc20Copied"] = "Адрес USDT TRC20 скопирован",
        ["UsdtTonCopied"] = "Адрес USDT TON скопирован",
        ["SupportActionFailed"] = "Не удалось выполнить действие. Попробуйте ещё раз.",
        ["Save"] = "Сохранить",
        ["Cancel"] = "Отмена",
        ["SignInWithTwitch"] = "Войти через Twitch",
        ["Filters"] = "Фильтры",
        ["Logout"] = "Выйти",
        ["SearchTooltip"] = "Поиск по нику или тексту сообщения",
        ["SearchMessages"] = "Поиск сообщений",
        ["UserFilterTooltip"] = "Фильтр по логину или имени",
        ["DecreaseFont"] = "Уменьшить размер шрифта",
        ["IncreaseFont"] = "Увеличить размер шрифта",
        ["TimeShort"] = "Время",
        ["Clear"] = "Очистить",
        ["BanUser"] = "Забанить",
        ["TimeoutTen"] = "Таймаут на 10 минут",
        ["TimeoutCustom"] = "Свой таймаут",
        ["CopyUsername"] = "Скопировать ник",
        ["CopyMessage"] = "Скопировать сообщение",
        ["OpenOnTwitch"] = "Открыть на Twitch",
        ["Send"] = "Отправить",
        ["EnterSendTooltip"] = "Enter отправляет, Shift+Enter переносит строку",
        ["NotSignedIn"] = "не выполнен вход",
        ["SignedIn"] = "подключено",
        ["SigningIn"] = "вход",
        ["AccountSignedIn"] = "Аккаунт",
        ["AccountSignedOut"] = "Аккаунт не подключён",
        ["ApiConnected"] = "API подключён",
        ["ApiConnecting"] = "API подключается",
        ["ApiDisconnected"] = "API отключён",
        ["ChatConnected"] = "Чат",
        ["ChatConnecting"] = "Чат подключается",
        ["ChatDisconnected"] = "Чат отключён",
        ["ChatError"] = "Ошибка чата",
        ["StreamLive"] = "В ЭФИРЕ",
        ["StreamOffline"] = "НЕ В ЭФИРЕ",
        ["EmptyConnectedTitle"] = "Здесь будут появляться сообщения чата",
        ["EmptyDisconnectedTitle"] = "Войдите через Twitch, чтобы подключить чат",
        ["SignInHelp"] = "Войдите через официальный Twitch login в браузере. После авторизации приложение подключит чат вашего канала.",
        ["MessageTooLong"] = "Сообщения Twitch ограничены 500 символами. Сократите сообщение и повторите попытку.",
        ["SignInFirst"] = "Сначала войдите в Twitch и подключите чат.",
        ["ChatNotConnected"] = "Чат ещё не подключён.",
        ["CannotModerateSelf"] = "Нельзя забанить или выдать таймаут самому себе.",
        ["ConfirmBanTitle"] = "Подтверждение бана",
        ["ConfirmBan"] = "Забанить пользователя {0} навсегда?",
        ["Error"] = "Ошибка",
        ["UnexpectedError"] = "Приложение поймало непредвиденную ошибку и продолжит работу, если это возможно.",
        ["OverlayCopied"] = "Overlay URL скопирован",
        ["OverlayUnavailable"] = "Тест оверлея недоступен.",
        ["OverlaySending"] = "Отправляю тестовое сообщение...",
        ["OverlayDisabled"] = "OBS оверлей выключен. Включите оверлей и повторите тест.",
        ["OverlayTestSent"] = "Тестовое сообщение отправлено: {0}",
        ["SettingsSaved"] = "Настройки сохранены",
        ["UnsavedSettingsHint"] = "Есть несохранённые изменения. Нажмите Сохранить или Отмена.",
        ["DurationMinutes"] = "Длительность, минуты",
        ["Reason"] = "Причина"
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["AppName"] = AppInfo.Name,
        ["AppTitle"] = AppInfo.Name,
        ["VersionLine"] = "version " + AppInfo.Version,
        ["Settings"] = "Settings",
        ["SettingsIntro"] = "Settings are grouped for streaming: program, chat, chat logs, OBS overlay, Twitch account, donate and advanced options.",
        ["ConnectTwitch"] = "Connect Twitch",
        ["ConnectTwitchIntro"] = "Choose full Twitch sign-in or watch a channel without authorization.",
        ["FullAccessDescription"] = "Full access: send messages, moderate chat and manage channel.",
        ["WatchChannelWithoutSignIn"] = "Watch channel without signing in",
        ["WatchOnlyDescription"] = "Read-only chat. Sending messages and moderation will be unavailable.",
        ["TwitchChannelName"] = "Twitch channel name",
        ["TwitchChannelNameRequired"] = "Enter a Twitch channel name.",
        ["ChannelSearchOffline"] = "Offline",
        ["ChannelSearchNoResults"] = "No channels found",
        ["ChannelSearchUnavailableWithoutAuth"] = "Online search is unavailable without authorization",
        ["WatchOnlyMode"] = "Watch-only mode",
        ["WatchOnlySendingUnavailable"] = "Sending messages is unavailable in watch-only mode",
        ["SignInToSend"] = "Sign in to send",
        ["ChangeWatchChannel"] = "Change watch channel",
        ["DisconnectFromChannel"] = "Disconnect from channel",
        ["WatchOnlyConnectFailed"] = "Failed to connect to chat in watch-only mode.",
        ["FullAccessMode"] = "Full access",
        ["CurrentMode"] = "Current mode",
        ["LastReadOnlyChannel"] = "Last read-only channel",
        ["Connect"] = "Connect",
        ["ChatReady"] = "Chat connected. New messages will appear here.",
        ["OAuthPort"] = "OAuth port",
        ["TwitchOAuthPortBusyTitle"] = "Twitch OAuth port is busy",
        ["OAuthPortBusy"] = "Twitch OAuth port is already used by another app.\nChange OAuth port in settings or close the app using this port.",
        ["OAuthOverlayPortConflict"] = "OAuth port and OBS overlay port must be different.",
        ["ChangeOAuthPortInSettings"] = "Change OAuth port in settings.",
        ["Program"] = "Program",
        ["Chat"] = "Chat",
        ["ChatLogs"] = "Chat Logs",
        ["Channels"] = "Channels",
        ["Streams"] = "Streams",
        ["Search"] = "Search",
        ["User"] = "User",
        ["OpenFolder"] = "Open folder",
        ["ExportTxt"] = "Export TXT",
        ["ExportJsonl"] = "Export JSONL",
        ["DeleteLog"] = "Delete log",
        ["Messages"] = "Messages",
        ["StreamTitle"] = "Stream title",
        ["StreamDate"] = "Stream date",
        ["LoggingEnabled"] = "Logging is enabled. The app saves only public chat messages, without tokens, OAuth data or private settings.",
        ["EnableChatLogging"] = "Enable chat logging",
        ["LogsFolder"] = "Logs folder",
        ["OpenLogsFolder"] = "Open logs folder",
        ["SaveJsonl"] = "Save JSONL",
        ["SaveTxt"] = "Save TXT",
        ["LogBadges"] = "Log badges",
        ["LogDeletedMessages"] = "Save deleted messages",
        ["MaxLogViewerMessages"] = "Max log viewer messages",
        ["AutoSplitLogsByStream"] = "Auto split logs by stream",
        ["NoChatLogs"] = "No chat logs found yet",
        ["LoadingLogs"] = "Loading logs...",
        ["ChatLogWriteFailed"] = "Failed to write chat log. Check the logs folder.",
        ["DeleteLogConfirm"] = "Delete the selected log session? This cannot be undone.",
        ["AllRoles"] = "All roles",
        ["BroadcasterRole"] = "Broadcaster",
        ["ModeratorRole"] = "Moderator",
        ["SubscriberRole"] = "Subscriber",
        ["VipRole"] = "VIP",
        ["ObsOverlay"] = "OBS Overlay",
        ["TwitchAccount"] = "Twitch / Account",
        ["Donate"] = "Donate",
        ["Advanced"] = "Advanced",
        ["Language"] = "Language",
        ["Theme"] = "Theme",
        ["Dark"] = "Dark",
        ["Light"] = "Light",
        ["SoundsDisabled"] = "Application sounds disabled",
        ["SoundsHelp"] = "Errors and warnings are shown visually, without Windows system sounds.",
        ["ToastNotifications"] = "Visual notifications",
        ["ReduceMotion"] = "Reduce motion",
        ["FontSize"] = "Font size",
        ["MessageLimit"] = "Message limit",
        ["ShowTimestamps"] = "Show timestamps",
        ["ShowBadges"] = "Show Twitch badges",
        ["EnableTwitchEmotes"] = "Enable Twitch emotes",
        ["EnableBttvEmotes"] = "Enable BTTV emotes",
        ["EnableSevenTvEmotes"] = "Enable 7TV emotes",
        ["EnableObsOverlay"] = "Enable overlay",
        ["OverlayUrl"] = "Overlay URL",
        ["CopyUrl"] = "Copy URL",
        ["OverlayPort"] = "Overlay port",
        ["OverlayMaxMessages"] = "Max messages on overlay",
        ["OverlayFontSize"] = "Font size",
        ["FadeOutSeconds"] = "Message fade out seconds",
        ["FadeOutHint"] = "0 = never disappear",
        ["BackgroundOpacity"] = "Background opacity",
        ["Align"] = "Align",
        ["Left"] = "Left",
        ["Center"] = "Center",
        ["Right"] = "Right",
        ["ShowEmotes"] = "Show emotes",
        ["TextShadow"] = "Text shadow",
        ["TestOverlayMessage"] = "Test overlay message",
        ["LogoutTwitch"] = "Logout from Twitch",
        ["ReconnectChat"] = "Reconnect chat",
        ["ChannelMode"] = "Channel mode",
        ["UseCustomChannel"] = "Connect to another channel where I am a moderator",
        ["ChannelLogin"] = "Channel login",
        ["BroadcasterId"] = "Broadcaster ID",
        ["AdvancedIntro"] = "Use these settings for development, a custom Twitch Client ID, or exact OAuth configuration.",
        ["UseCustomClientId"] = "Use custom Twitch Client ID",
        ["CustomClientId"] = "Custom Twitch Client ID",
        ["OAuthRedirectUri"] = "OAuth Redirect URI",
        ["RedirectHelp"] = "Must match the Redirect URL in Twitch Developer Console. Default: http://localhost:17654/. OBS overlay uses a separate port: http://localhost:17655/overlay/chat.",
        ["SupportDeveloper"] = "Support the developer",
        ["SupportDeveloperDescription"] = "You can support the development of WitherChat using any convenient option.",
        ["Open"] = "Open",
        ["Copy"] = "Copy",
        ["AddressCopied"] = "Address copied",
        ["Boosty"] = "Boosty",
        ["DonationAlerts"] = "DonationAlerts",
        ["Twitch"] = "Twitch",
        ["YouTube"] = "YouTube",
        ["UsdtTrc20"] = "USDT TRC20",
        ["UsdtTon"] = "USDT TON",
        ["UsdtTrc20Copied"] = "USDT TRC20 address copied",
        ["UsdtTonCopied"] = "USDT TON address copied",
        ["SupportActionFailed"] = "The action could not be completed. Please try again.",
        ["Save"] = "Save",
        ["Cancel"] = "Cancel",
        ["SignInWithTwitch"] = "Sign in with Twitch",
        ["Filters"] = "Filters",
        ["Logout"] = "Logout",
        ["SearchTooltip"] = "Search by username or message text",
        ["SearchMessages"] = "Search messages",
        ["UserFilterTooltip"] = "Filter by login or display name",
        ["DecreaseFont"] = "Decrease font size",
        ["IncreaseFont"] = "Increase font size",
        ["TimeShort"] = "Time",
        ["Clear"] = "Clear",
        ["BanUser"] = "Ban user",
        ["TimeoutTen"] = "Timeout 10 minutes",
        ["TimeoutCustom"] = "Custom timeout",
        ["CopyUsername"] = "Copy username",
        ["CopyMessage"] = "Copy message",
        ["OpenOnTwitch"] = "Open on Twitch",
        ["Send"] = "Send",
        ["EnterSendTooltip"] = "Enter sends, Shift+Enter inserts a line break",
        ["NotSignedIn"] = "not signed in",
        ["SignedIn"] = "connected",
        ["SigningIn"] = "signing in",
        ["AccountSignedIn"] = "Signed in",
        ["AccountSignedOut"] = "Signed out",
        ["ApiConnected"] = "API connected",
        ["ApiConnecting"] = "API connecting",
        ["ApiDisconnected"] = "API disconnected",
        ["ChatConnected"] = "Chat",
        ["ChatConnecting"] = "Chat connecting",
        ["ChatDisconnected"] = "Chat disconnected",
        ["ChatError"] = "Chat error",
        ["StreamLive"] = "LIVE",
        ["StreamOffline"] = "OFFLINE",
        ["EmptyConnectedTitle"] = "Chat messages will appear here",
        ["EmptyDisconnectedTitle"] = "Sign in with Twitch to connect chat",
        ["SignInHelp"] = "Sign in through the official Twitch login page in your browser. After authorization, the app will connect your channel chat.",
        ["MessageTooLong"] = "Twitch chat messages are limited to 500 characters. Shorten the message and try again.",
        ["SignInFirst"] = "Sign in with Twitch and connect chat first.",
        ["ChatNotConnected"] = "Chat is not connected yet.",
        ["CannotModerateSelf"] = "You cannot ban or timeout yourself.",
        ["ConfirmBanTitle"] = "Ban confirmation",
        ["ConfirmBan"] = "Ban user {0} permanently?",
        ["Error"] = "Error",
        ["UnexpectedError"] = "The app caught an unexpected error and will continue if possible.",
        ["OverlayCopied"] = "Overlay URL copied",
        ["OverlayUnavailable"] = "Overlay test is unavailable.",
        ["OverlaySending"] = "Sending test message...",
        ["OverlayDisabled"] = "OBS overlay is disabled. Enable overlay and try again.",
        ["OverlayTestSent"] = "Test message sent: {0}",
        ["SettingsSaved"] = "Settings saved",
        ["UnsavedSettingsHint"] = "You have unsaved changes. Use Save or Cancel.",
        ["DurationMinutes"] = "Duration, minutes",
        ["Reason"] = "Reason"
    };

    public static string NormalizeLanguage(string? language)
    {
        if (string.IsNullOrWhiteSpace(language))
        {
            return Russian;
        }

        var value = language.Trim();
        if (ContainsMojibake(value))
        {
            return Russian;
        }

        if (string.Equals(value, "en", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "en-US", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "english", StringComparison.OrdinalIgnoreCase))
        {
            return English;
        }

        if (string.Equals(value, "ru", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "ru-RU", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "russian", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, "русский", StringComparison.OrdinalIgnoreCase))
        {
            return Russian;
        }

        return Russian;
    }

    public static string Get(string? language, string key)
    {
        var source = NormalizeLanguage(language) == English ? En : Ru;
        return source.TryGetValue(key, out var value) && !ContainsMojibake(value) ? value : key;
    }

    public static void ApplyToResources(string? language)
    {
        var source = NormalizeLanguage(language) == English ? En : Ru;
        foreach (var pair in source)
        {
            Application.Current.Resources[pair.Key] = ContainsMojibake(pair.Value) ? pair.Key : pair.Value;
        }
    }

    public static bool ContainsMojibake(string? value)
    {
        return !string.IsNullOrEmpty(value) &&
               (value.Contains('\u00D0') ||
                value.Contains('\u00D1') ||
                value.Contains('\uFFFD'));
    }
}
